CFLAGS = -Wall -pedantic -std=c99
CC = gcc

error: ../../build/quadSolverSqrt.o ../../build/quadSolverRoots.o
	${CC} ${CFLAGS} -o error error.c ../../build/quadSolverSqrt.o ../../build/quadSolverRoots.o -lm
