all:
	gcc -Wall -Wpedantic -std=c99 -g squareRoot.c -o squareRoot -lm

use:
	./squareRoot 2
	./squareRoot 3
	./squareRoot 4
	./squareRoot 16
	./squareRoot 5
	./squareRoot 4.84
	./squareRoot -1
	./squareRoot a
